#!/bin/bash

unset DISPLAY
export JAVA_OPTS="-Djava.awt.headless=true -Xms64m -Xmx64m"
export X509_USER_PROXY=~/.grid/grid.proxy
java ${JAVA_OPTS} -cp /usr/local/lib/grisu/goji-binary.jar nz.org.nesi.goji.view.GojiCli "$@"

